---
exclude_paths: [
    '*',    
    'spa/*',
    'spa/css/**',
    'spa/dist/**',
    'spa/webpack/**',
    'webhost/*',
    'webhost/certs/**',
    'cloud/lambda-edge/*',
    'cloud/lambda-edge/test/**',
    'cloud/deployment/**'
]
