---
exclude_paths: [
    '*',
    'doc/**',
    'deployment/**',
    'demoapp/*',
    'demoapp/css/**',
    'demoapp/dist/**',
    'demoapp/webpack/**',
    'webhost/*',
    'cloudfront-extensions/*'
]
