---
exclude_paths:
  - '*'
  - 'doc/**'
  - 'deployment/**'
  - 'spa/demoapp/*'
  - 'spa/shellapp/*'
  - 'spa/build/**'
  - 'webhost/*'
  - 'cloudfront-extensions/*'
  - 'cloudfront-extensions/environments/**'
  - 'cloudfront-extensions/test/**'
