---
exclude_paths:
  - '*'
  - 'doc/**'
  - 'deployment/**'
  - 'demoapp/*'
  - 'shellapp/*'
  - 'webhost/*'
  - 'cloudfront-extensions/*'
  - 'cloudfront-extensions/environments/**'
  - 'cloudfront-extensions/test/**'
