---
#
# Only use codacy for the src folders of the webhost, shellapp and demoapp
#
exclude_paths:
  - '*',
  - 'doc/**',
  - 'deployment/**',
  - 'demoapp/*',
  - 'demoapp/build/**',
  - 'shellapp/*',
  - 'shellapp/build/**',
  - 'webhost/*',
  - 'cloudfront-extensions/*'

#
# Duplication across demoapp and shellapp is intentional
#
engines:
  duplication:
    enabled: true
    exclude_paths:
      - 'shellapp/**'
      - 'demoapp/**'
