---
exclude_paths: [
    '*',
    'doc/**',
    'deployment/**',
    'demoapp/*',
    'demoapp/webpack/**',
    'shellapp/*',
    'shellapp/webpack/**',
    'webhost/*',
    'cloudfront-extensions/*'
]
