#
# The certificate used by our Web Host inside the cluster
#

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhost-svc-internal-cert
spec:
  secretName: webhost-svc-internal-cert
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: webhost-svc.default.svc
  dnsNames:
  - webhost-svc
  - webhost-svc.default.svc
  - webhost-svc.default.svc.cluster.local
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: webhost-pkcs12-password
        key: password